server:
  port: 8459
logging:
  file: /java/C2S_LOGS/c2s-ui-api/c2sUiApi.log
info:
  component: C2S UI API
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
security:
  oauth2:
    client:
      client-id: c2s-ui-api
c2s:
  c2s-ui:
    patient-permissions:
      health-information-enabled: false

  c2s-ui-api:
    # Please configure valid config below to connect to UAA server
    # Configure base-url, client-id, client-secret per environment
    oauth2:
      base-url: http://localhost/uaa
      client:
        client-id: c2s-ui
        client-secret: changeit
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /c2s-ui-api